ALTER TABLE `oxorder` ADD `MUDEPREPAYMENTREMINDED` DATE NULL;

INSERT INTO `oxcontents` (
`OXID`, `OXLOADID`, `OXSHOPID`, `OXSNIPPET`, `OXTYPE`, `OXACTIVE`, `OXACTIVE_1`, `OXPOSITION`, `OXTITLE`, `OXCONTENT`, `OXTITLE_1`, `OXCONTENT_1`, `OXACTIVE_2`, `OXTITLE_2`, `OXCONTENT_2`, `OXACTIVE_3`, `OXTITLE_3`, `OXCONTENT_3`, `OXCATID`, `OXFOLDER`, `OXTERMVERSION`, `OXTIMESTAMP`
) VALUES (
'mudeprepaymentcustomeremail',
'mudeprepaymentcustomeremail',
'oxbaseshop',
1, 0, 1, 1, '',
'Vorkasseerinnerung zur Bestellung', 'Guten Tag [{ $order->oxorder__oxbillsal->value|oxmultilangsal }] [{ $order->oxorder__oxbilllname->value }],\\r\\n<br/><br/>\\r\\nSie haben am [{$order->oxorder__oxorderdate->value}] Uhr bei [{ $shop->oxshops__oxname->getRawValue() }] eine Onlinebestellung aufgegeben.\\r\\n<br/><br/>\\r\\nBislang ist Ihre ausstehende Zahlung noch nicht auf unserem Konto eingegangen. Sie erhalten nachfolgend noch einmal alle erforderlichen Zahlungsinformationen:\\r\\n<br/><br/>\\r\\nRechnungsbetrag: [{ $order->oxorder__oxtotalordersum->value|number_format:2:",":"."}] [{ $order->oxorder__oxcurrency->value}]\\r\\n<br/><br/>\\r\\nBankname: [{$shop->oxshops__oxbankname->value}]<br/>\\r\\nKontoinhaber: [{$shop->oxshops__oxfname->value}] [{$shop->oxshops__oxlname->value}]<br/>\\r\\nBankleitzahl: [{$shop->oxshops__oxbankcode->value}]<br/>\\r\\nKontonummer: [{$shop->oxshops__oxbanknumber->value}]<br/>\\r\\nBIC: [{$shop->oxshops__oxbiccode->value}]<br/>\\r\\nIBAN: [{$shop->oxshops__oxibannumber->value}]<br/>\\r\\nVerwendungszweck: [{$order->oxorder__oxordernr->value}]<br/>\\r\\n<br/><br/>\\r\\nBitte überweisen Sie den offenen Betrag in den nächsten Tagen auf unser Bankkonto. Ihre Bestellung wird sofort nach Zahlungseingang bearbeitet.\\r\\n<br/><br/>\\r\\nViele Grüße,\\r\\n<br/><br/>\\r\\n[{ $shop->oxshops__oxname->getRawValue() }]',
'Vorkasseerinnerung zur Bestellung', 'Guten Tag [{ $order->oxorder__oxbillsal->value|oxmultilangsal }] [{ $order->oxorder__oxbilllname->value }],\\r\\n<br/><br/>\\r\\nSie haben am [{$order->oxorder__oxorderdate->value}] Uhr bei [{ $shop->oxshops__oxname->getRawValue() }] eine Onlinebestellung aufgegeben.\\r\\n<br/><br/>\\r\\nBislang ist Ihre ausstehende Zahlung noch nicht auf unserem Konto eingegangen. Sie erhalten nachfolgend noch einmal alle erforderlichen Zahlungsinformationen:\\r\\n<br/><br/>\\r\\nRechnungsbetrag: [{ $order->oxorder__oxtotalordersum->value|number_format:2:",":"."}] [{ $order->oxorder__oxcurrency->value}]\\r\\n<br/><br/>\\r\\nBankname: [{$shop->oxshops__oxbankname->value}]<br/>\\r\\nKontoinhaber: [{$shop->oxshops__oxfname->value}] [{$shop->oxshops__oxlname->value}]<br/>\\r\\nBankleitzahl: [{$shop->oxshops__oxbankcode->value}]<br/>\\r\\nKontonummer: [{$shop->oxshops__oxbanknumber->value}]<br/>\\r\\nBIC: [{$shop->oxshops__oxbiccode->value}]<br/>\\r\\nIBAN: [{$shop->oxshops__oxibannumber->value}]<br/>\\r\\nVerwendungszweck: [{$order->oxorder__oxordernr->value}]<br/>\\r\\n<br/><br/>\\r\\nBitte überweisen Sie den offenen Betrag in den nächsten Tagen auf unser Bankkonto. Ihre Bestellung wird sofort nach Zahlungseingang bearbeitet.\\r\\n<br/><br/>\\r\\nViele Grüße,\\r\\n<br/><br/>\\r\\n[{ $shop->oxshops__oxname->getRawValue() }]',
1,
'Vorkasseerinnerung zur Bestellung', 'Guten Tag [{ $order->oxorder__oxbillsal->value|oxmultilangsal }] [{ $order->oxorder__oxbilllname->value }],\\r\\n<br/><br/>\\r\\nSie haben am [{$order->oxorder__oxorderdate->value}] Uhr bei [{ $shop->oxshops__oxname->getRawValue() }] eine Onlinebestellung aufgegeben.\\r\\n<br/><br/>\\r\\nBislang ist Ihre ausstehende Zahlung noch nicht auf unserem Konto eingegangen. Sie erhalten nachfolgend noch einmal alle erforderlichen Zahlungsinformationen:\\r\\n<br/><br/>\\r\\nRechnungsbetrag: [{ $order->oxorder__oxtotalordersum->value|number_format:2:",":"."}] [{ $order->oxorder__oxcurrency->value}]\\r\\n<br/><br/>\\r\\nBankname: [{$shop->oxshops__oxbankname->value}]<br/>\\r\\nKontoinhaber: [{$shop->oxshops__oxfname->value}] [{$shop->oxshops__oxlname->value}]<br/>\\r\\nBankleitzahl: [{$shop->oxshops__oxbankcode->value}]<br/>\\r\\nKontonummer: [{$shop->oxshops__oxbanknumber->value}]<br/>\\r\\nBIC: [{$shop->oxshops__oxbiccode->value}]<br/>\\r\\nIBAN: [{$shop->oxshops__oxibannumber->value}]<br/>\\r\\nVerwendungszweck: [{$order->oxorder__oxordernr->value}]<br/>\\r\\n<br/><br/>\\r\\nBitte überweisen Sie den offenen Betrag in den nächsten Tagen auf unser Bankkonto. Ihre Bestellung wird sofort nach Zahlungseingang bearbeitet.\\r\\n<br/><br/>\\r\\nViele Grüße,\\r\\n<br/><br/>\\r\\n[{ $shop->oxshops__oxname->getRawValue() }]',
0,
'Vorkasseerinnerung zur Bestellung', 'Guten Tag [{ $order->oxorder__oxbillsal->value|oxmultilangsal }] [{ $order->oxorder__oxbilllname->value }],\\r\\n<br/><br/>\\r\\nSie haben am [{$order->oxorder__oxorderdate->value}] Uhr bei [{ $shop->oxshops__oxname->getRawValue() }] eine Onlinebestellung aufgegeben.\\r\\n<br/><br/>\\r\\nBislang ist Ihre ausstehende Zahlung noch nicht auf unserem Konto eingegangen. Sie erhalten nachfolgend noch einmal alle erforderlichen Zahlungsinformationen:\\r\\n<br/><br/>\\r\\nRechnungsbetrag: [{ $order->oxorder__oxtotalordersum->value|number_format:2:",":"."}] [{ $order->oxorder__oxcurrency->value}]\\r\\n<br/><br/>\\r\\nBankname: [{$shop->oxshops__oxbankname->value}]<br/>\\r\\nKontoinhaber: [{$shop->oxshops__oxfname->value}] [{$shop->oxshops__oxlname->value}]<br/>\\r\\nBankleitzahl: [{$shop->oxshops__oxbankcode->value}]<br/>\\r\\nKontonummer: [{$shop->oxshops__oxbanknumber->value}]<br/>\\r\\nBIC: [{$shop->oxshops__oxbiccode->value}]<br/>\\r\\nIBAN: [{$shop->oxshops__oxibannumber->value}]<br/>\\r\\nVerwendungszweck: [{$order->oxorder__oxordernr->value}]<br/>\\r\\n<br/><br/>\\r\\nBitte überweisen Sie den offenen Betrag in den nächsten Tagen auf unser Bankkonto. Ihre Bestellung wird sofort nach Zahlungseingang bearbeitet.\\r\\n<br/><br/>\\r\\nViele Grüße,\\r\\n<br/><br/>\\r\\n[{ $shop->oxshops__oxname->getRawValue() }]',
'3ef0d93e75e4df9a7680df4cd73309d5', 'CMSFOLDER_EMAILS', '', NOW());
